refactor: Update wezterm configuration to enhance bell notification handling for specific processes
Signed-off-by: Marcel Hild <hild@b4mad.net>

diff --git a/git_template/hooks/pre-commit b/git_template/hooks/pre-commit
--- a/git_template/hooks/pre-commit
+++ b/git_template/hooks/pre-commit
@@ -1,17 +1,20 @@
-#!/bin/sh
+#!/usr/bin/env bash
+# File generated by pre-commit: https://pre-commit.com
+# ID: 138fd403232d2ddd5efb44317e38bf03
 
-local_hook="$HOME"/.git_template.local/hooks/pre-commit
+# start templated
+INSTALL_PYTHON=/opt/homebrew/opt/pre-commit/libexec/bin/python3.12
+ARGS=(hook-impl --config=.pre-commit-config.yaml --hook-type=pre-commit)
+# end templated
 
-if [ -f "$local_hook" ]; then
-  . "$local_hook"
-fi
+HERE="$(cd "$(dirname "$0")" && pwd)"
+ARGS+=(--hook-dir "$HERE" -- "$@")
 
-if [ -f .rubocop.yml ]; then
-  if [ -f .git/hooks/pre-commit-rubocop.rb ]; then
-     .git/hooks/pre-commit-rubocop.rb
-     status=$?
-     if test $status -ne 0; then
-        exit $status
-     fi
-  fi
+if [ -x "$INSTALL_PYTHON" ]; then
+    exec "$INSTALL_PYTHON" -mpre_commit "${ARGS[@]}"
+elif command -v pre-commit > /dev/null; then
+    exec pre-commit "${ARGS[@]}"
+else
+    echo '`pre-commit` not found.  Did you forget to activate your virtualenv?' 1>&2
+    exit 1
 fi
