stuff

diff --git a/git_template/hooks/pre-push b/git_template/hooks/pre-push
--- a/git_template/hooks/pre-push
+++ b/git_template/hooks/pre-push
@@ -11,20 +11,20 @@ if [[ -z "$OVERRIDE" ]]; then
 fi
 
 # Prevent pushes of old CFME history
-if [[ -z "$OVERRIDE_HISTORY" ]]; then
-  init_sha="d34d87219092431c22c88a5865f25f9942ebe1ea"
-  git rev-parse --verify --quiet ${init_sha}^{commit} > /dev/null  # Verify the grafted history exists
-  if [ $? -eq 0 ]; then
-    IFS=' '
-    while read local_ref local_sha remote_ref remote_sha; do
-      if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then # Allow deleting branches
-        merge_sha=`git merge-base $local_sha $init_sha`
-        if [[ "$merge_sha" != $init_sha ]]; then
-          echo "error: You cannot push commits from the old CFME history to $1!"
-          echo "error: Set OVERRIDE_HISTORY=true on this command to allow pushing to 5.2.x"
-          exit 1
-        fi
-      fi
-    done
-  fi
-fi
+#if [[ -z "$OVERRIDE_HISTORY" ]]; then
+#  init_sha="d34d87219092431c22c88a5865f25f9942ebe1ea"
+#  git rev-parse --verify --quiet ${init_sha}^{commit} > /dev/null  # Verify the grafted history exists
+#  if [ $? -eq 0 ]; then
+#    IFS=' '
+#    while read local_ref local_sha remote_ref remote_sha; do
+#      if [[ "$local_sha" != "0000000000000000000000000000000000000000" ]]; then # Allow deleting branches
+#        merge_sha=`git merge-base $local_sha $init_sha`
+#        if [[ "$merge_sha" != $init_sha ]]; then
+#          echo "error: You cannot push commits from the old CFME history to $1!"
+#          echo "error: Set OVERRIDE_HISTORY=true on this command to allow pushing to 5.2.x"
+#          exit 1
+#        fi
+#      fi
+#    done
+#  fi
+#fi
